- job:
    name: ansible-role-nginx-base
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-nginx

- job:
    name: ansible-role-nginx
    parent: ansible-role-nginx-base

- job:
    name: ansible-role-nginx-fedora-latest
    parent: ansible-role-nginx
    nodeset: fedora-latest

- job:
    name: ansible-role-nginx-ubuntu-bionic
    parent: ansible-role-nginx
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-nginx-fedora-latest
        - ansible-role-nginx-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-nginx-fedora-latest
        - ansible-role-nginx-ubuntu-bionic
        - tox-linters
